### PR TITLE
[WIP] Add module to parse the JH lookup table

### PR DESCRIPTION
**Pull request by MatMoore**
# Summary
This is basically a rewrite of the JH import to clean up the region information, which was really unreliable.

It uses the information provided at https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/UID_ISO_FIPS_LookUp_Table.csv to link daily reports to a canonical location (where possible).

Based on this, we are now able to filter data based on country, and by the scope of the report (country/region, province/state, or administrative area). Previously this was not possible for all locations due to the inconsistency in how they were reported.

# Reviewing this PR
I ended up refactoring this quite a lot so I would recommend reviewing this file by file rather than going through individual commits.

These are the main things I've changed:

## Helper classes
The `region_info` module contains multiple helper classes which are only used by the import.

The main one is `Matcher`, which takes a `RegionNames` object (a named tuple of country/region, province/state, and admin2), and maps it to a `RegionInfo` object, which contains all the info we know from the lookup table.

```python
RegionInfo(
  identified_region=IdentifiedRegion(uid=28, fips=None, iso2='AG', iso3='ATG', scope=<Scope.COUNTRY_REGION: 1>),
  region_names=RegionNames(admin2=None, province_state=None, country_region='Antigua and Barbuda'),
  population=97928,
  combined_key='Antigua and Barbuda',
  coordinates=LatLong(latitude=17.0608, longitude=-61.7964)
)
```

This includes some info we're not actually using yet (population and coordinates).

## Data cleaning
Because there was such a discrepancy between the data in the daily reports and the data in the lookup table, I wrote a bunch of code to normalise all the place names. This basically takes a `RegionNames` objects and maps it into another `RegionNames` that can be matched. This extends and replaces all the existing code for cleaning these names.

I've now added tests for this code so it should be easier to refactor this.

## Schema changes
At a database level, this is implemented as a foreign key to a new jh_region_info table.

This branch also introduced alembic so that we can update the existing database rather than recreating it all from scratch. This also cleans up the old version of the jh_daily_report from before we renamed them to add the jh_ prefix.

## API changes
The API now returns the region details as an object. The existing region fields are left unchanged, because I wanted to keep this backwards compatible for the time being just in case people are already using this and still depending on the old names.

You can also filter on ISO country codes and the scope field (see example below).

## CLI
There are now 3 commands on the CLI:

- `jh` is the existing import
-` jh_regions` imports the lookup table. We will need to run this once, and repeat it if there are any updates, but this happens infrequently.
- `jh_regions_link`  adds the `jh_id` for any reports already in the database. This is a one off task so we don't have to run the whole import again.

But by doing this I uncovered even more data quality issues with the daily reports, including some cases where there seems to be multiple reports for the same place, using different names.

I ended up writing loads more python code to map similar-but-different names to the same things, and filter out some places that are not even included in the lookup table, like city data for the US.

Since this is a really big change, I want to write some tests for this before merging it, but I think it's a big improvement on what we had before.

## Package structure
As there is now a lot of code for this import, I've moved everything into a new `jh_import` subpackage and got rid of the `import_jh` module.

# Example of new country filtering using ISO codes
Here's an example response from calling `http://127.0.0.1:8000/v1/jh/daily-reports/?country_code_iso2=GB&scope=Country_Region` on this branch

```json
          {
            "id": 100709,
            "country_region": "United Kingdom",
            "province_state": null,
            "fips": null,
            "admin2": null,
            "last_update": "2020-04-04T23:34:00",
            "confirmed": 41903,
            "deaths": 4313,
            "recovered": 135,
            "region_info": {
              "uid": 826,
              "scope": "Country_Region",
              "country_code_iso2": "GB",
              "country_code_iso3": "GBR",
              "country_region": "United Kingdom",
              "province_state": null,
              "fips": null,
              "admin2": null
            }
          }
```

In this case the details are the same, but the stuff in "region_info" is guaranteed to be normalised across the whole dataset, unlike the other fields which change all the time.

# Deployment plan
Because this is a big change I suggest we test this process before deploying.

I think these are the steps:

- [ ] Take a backup from live, to test the following steps on:
- [ ] Stamp the database as version 1 `alembic stamp 8497fb70170b`
- [ ] Run alembic migrations `alembic upgrade head`
- [ ] Run `python import_data.py jh_regions`
- [ ] Run `python import_data.py jh_regions_link`
- [ ] Check that only a small number of reports have null jh_id: `select country_region, province_state, admin2, last_update from jh_daily_reports where jh_id is null;`
- [ ] When new data is released run `python import_data.py jh --latest` and make sure there are no reported errors
- [ ] Make sure `python import_data.py jh` runs to completion on an empty db

### CODE REVIEW

**Comment by MatMoore** [comment]
Once again, this ended up way more complicated than I thought. 😅 

Using the lookup table I was able to link most of the reports to a concrete location, which means we can filter by country reliably now 🎉 

But by doing this I uncovered even more data quality issues with the daily reports, including some cases where there seems to be multiple reports for the same place, using different names.

I ended up writing loads more python code to map similar-but-different names to the same things, and filter out some places that are not even included in the lookup table, like city data for the US.

Here's an example response from calling `http://127.0.0.1:8000/v1/jh/daily-reports/?country_code_iso2=GB&scope=Country_Region` on this branch

```json
          {
            "id": 100709,
            "country_region": "United Kingdom",
            "province_state": null,
            "fips": null,
            "admin2": null,
            "last_update": "2020-04-04T23:34:00",
            "confirmed": 41903,
            "deaths": 4313,
            "recovered": 135,
            "region_info": {
              "uid": 826,
              "scope": "Country_Region",
              "country_code_iso2": "GB",
              "country_code_iso3": "GBR",
              "country_region": "United Kingdom",
              "province_state": null,
              "fips": null,
              "admin2": null
            }
          }
```

In this case the details are the same, but the stuff in "region_info" is guaranteed to be normalised across the whole dataset, unlike the other fields which change all the time.

Here's the current output of running the import from the beginning:

```
(env) MacBook-Air:covid-api mat$ python import_data.py jh --all
Importing data for 2020-02-29
Number of processed locations: 105
Number of duplicate locations: 0
Number of resolved duplicate locations: 0
Number of ignored locations: 14
Importing data for 2020-03-01
Number of processed locations: 111
Number of duplicate locations: 0
Number of resolved duplicate locations: 0
Number of ignored locations: 14
Importing data for 2020-03-02
Number of processed locations: 129
Number of duplicate locations: 0
Number of resolved duplicate locations: 0
Number of ignored locations: 12
Importing data for 2020-03-03
Number of processed locations: 139
Number of duplicate locations: 0
Number of resolved duplicate locations: 0
Number of ignored locations: 12
Importing data for 2020-03-04
Number of processed locations: 148
Number of duplicate locations: 0
Number of resolved duplicate locations: 0
Number of ignored locations: 12
Importing data for 2020-03-05
Number of processed locations: 160
Number of duplicate locations: 0
Number of resolved duplicate locations: 0
Number of ignored locations: 13
Importing data for 2020-03-06
Number of processed locations: 183
Number of duplicate locations: 0
Number of resolved duplicate locations: 0
Number of ignored locations: 16
Importing data for 2020-03-07
Number of processed locations: 211
Number of duplicate locations: 0
Number of resolved duplicate locations: 0
Number of ignored locations: 14
Importing data for 2020-03-08
Warning: Ambiguous record DailyReport(id=symbol('NO_VALUE'), country_region='Republic of Ireland', province_state=None, fips=None, admin2=None, last_update=datetime.datetime(2020, 3, 8, 21, 3, 3), confirmed=21, deaths=0, recovered=0, jh_id=372): other record has confirmed=19, deaths=0, recovered=0
Number of processed locations: 238
Number of duplicate locations: 1
Number of resolved duplicate locations: 0
Number of ignored locations: 16
Importing data for 2020-03-09
Number of processed locations: 256
Number of duplicate locations: 0
Number of resolved duplicate locations: 0
Number of ignored locations: 10
Importing data for 2020-03-10
Number of processed locations: 204
Number of duplicate locations: 0
Number of resolved duplicate locations: 0
Number of ignored locations: 2
Importing data for 2020-03-11
Number of processed locations: 212
Number of duplicate locations: 2
Number of resolved duplicate locations: 2
Number of ignored locations: 2
Importing data for 2020-03-12
Number of processed locations: 214
Number of duplicate locations: 2
Number of resolved duplicate locations: 2
Number of ignored locations: 2
Importing data for 2020-03-13
Number of processed locations: 229
Number of duplicate locations: 0
Number of resolved duplicate locations: 0
Number of ignored locations: 1
Importing data for 2020-03-14
Number of processed locations: 244
Number of duplicate locations: 1
Number of resolved duplicate locations: 1
Number of ignored locations: 4
Importing data for 2020-03-15
Number of processed locations: 254
Number of duplicate locations: 0
Number of resolved duplicate locations: 0
Number of ignored locations: 4
Importing data for 2020-03-16
Warning: Ambiguous record DailyReport(id=symbol('NO_VALUE'), country_region='French Guiana', province_state=None, fips=None, admin2=None, last_update=datetime.datetime(2020, 3, 16, 14, 38, 46), confirmed=11, deaths=0, recovered=0, jh_id=254): other record has confirmed=5, deaths=0, recovered=0
Warning: Ambiguous record DailyReport(id=symbol('NO_VALUE'), country_region='Guadeloupe', province_state=None, fips=None, admin2=None, last_update=datetime.datetime(2020, 3, 16, 14, 38, 45), confirmed=6, deaths=0, recovered=0, jh_id=312): other record has confirmed=3, deaths=0, recovered=0
Warning: Ambiguous record DailyReport(id=symbol('NO_VALUE'), country_region='US', province_state='Puerto Rico', fips=None, admin2=None, last_update=datetime.datetime(2020, 3, 16, 0, 22, 11), confirmed=5, deaths=0, recovered=0, jh_id=630): other record has confirmed=3, deaths=0, recovered=0
Warning: Ambiguous record DailyReport(id=308135, country_region='Congo (Kinshasa)', province_state=None, fips=None, admin2=None, last_update=datetime.datetime(2020, 3, 13, 22, 22, 2), confirmed=2, deaths=0, recovered=0, jh_id=180): other record has confirmed=1, deaths=0, recovered=0
Number of processed locations: 262
Number of duplicate locations: 6
Number of resolved duplicate locations: 2
Number of ignored locations: 4
Importing data for 2020-03-17
Warning: Ambiguous record DailyReport(id=symbol('NO_VALUE'), country_region='Guadeloupe', province_state=None, fips=None, admin2=None, last_update=datetime.datetime(2020, 3, 17, 10, 53, 3), confirmed=18, deaths=0, recovered=0, jh_id=312): other record has confirmed=6, deaths=0, recovered=0
Warning: Ambiguous record DailyReport(id=308482, country_region='French Guiana', province_state=None, fips=None, admin2=None, last_update=datetime.datetime(2020, 3, 16, 14, 38, 46), confirmed=11, deaths=0, recovered=0, jh_id=254): other record has confirmed=7, deaths=0, recovered=0
Number of processed locations: 265
Number of duplicate locations: 7
Number of resolved duplicate locations: 5
Number of ignored locations: 4
Importing data for 2020-03-18
Warning: Ambiguous record DailyReport(id=symbol('NO_VALUE'), country_region='Aruba', province_state=None, fips=None, admin2=None, last_update=datetime.datetime(2020, 3, 18, 11, 53, 4), confirmed=4, deaths=0, recovered=0, jh_id=533): other record has confirmed=2, deaths=0, recovered=0
Number of processed locations: 271
Number of duplicate locations: 10
Number of resolved duplicate locations: 9
Number of ignored locations: 3
Importing data for 2020-03-19
Warning: Ambiguous record DailyReport(id=308900, country_region='Aruba', province_state=None, fips=None, admin2=None, last_update=datetime.datetime(2020, 3, 18, 11, 53, 4), confirmed=4, deaths=0, recovered=0, jh_id=533): other record has confirmed=2, deaths=0, recovered=0
Warning: Ambiguous record DailyReport(id=symbol('NO_VALUE'), country_region='US', province_state='Virgin Islands', fips=None, admin2=None, last_update=datetime.datetime(2020, 3, 19, 16, 13, 38), confirmed=3, deaths=0, recovered=0, jh_id=850): other record has confirmed=2, deaths=0, recovered=0
Number of processed locations: 277
Number of duplicate locations: 12
Number of resolved duplicate locations: 10
Number of ignored locations: 3
Importing data for 2020-03-20
Number of processed locations: 286
Number of duplicate locations: 10
Number of resolved duplicate locations: 10
Number of ignored locations: 3
Importing data for 2020-03-21
Warning: Ambiguous record DailyReport(id=symbol('NO_VALUE'), country_region='Cabo Verde', province_state=None, fips=None, admin2=None, last_update=datetime.datetime(2020, 3, 21, 15, 13, 46), confirmed=3, deaths=0, recovered=0, jh_id=132): other record has confirmed=1, deaths=0, recovered=0
Number of processed locations: 290
Number of duplicate locations: 11
Number of resolved duplicate locations: 10
Number of ignored locations: 3
Importing data for 2020-03-22
Warning: No match found for RegionNames(admin2=None, province_state='External territories', country_region='Australia')
Warning: No match found for RegionNames(admin2=None, province_state='Jervis Bay Territory', country_region='Australia')
Number of processed locations: 3402
Number of duplicate locations: 6
Number of resolved duplicate locations: 6
Number of ignored locations: 7
Importing data for 2020-03-23
Number of processed locations: 3411
Number of duplicate locations: 2
Number of resolved duplicate locations: 2
Number of ignored locations: 0
Importing data for 2020-03-24
Number of processed locations: 3414
Number of duplicate locations: 2
Number of resolved duplicate locations: 2
Number of ignored locations: 0
Importing data for 2020-03-25
Number of processed locations: 3418
Number of duplicate locations: 2
Number of resolved duplicate locations: 2
Number of ignored locations: 0
Importing data for 2020-03-26
Number of processed locations: 3420
Number of duplicate locations: 1
Number of resolved duplicate locations: 1
Number of ignored locations: 0
Importing data for 2020-03-27
Number of processed locations: 3428
Number of duplicate locations: 1
Number of resolved duplicate locations: 1
Number of ignored locations: 0
Importing data for 2020-03-28
Number of processed locations: 3429
Number of duplicate locations: 1
Number of resolved duplicate locations: 1
Number of ignored locations: 0
Importing data for 2020-03-29
Number of processed locations: 3433
Number of duplicate locations: 1
Number of resolved duplicate locations: 1
Number of ignored locations: 0
Importing data for 2020-03-30
Number of processed locations: 3438
Number of duplicate locations: 1
Number of resolved duplicate locations: 1
Number of ignored locations: 0
Importing data for 2020-03-31
Number of processed locations: 2434
Number of duplicate locations: 0
Number of resolved duplicate locations: 0
Number of ignored locations: 0
Importing data for 2020-04-01
Number of processed locations: 2483
Number of duplicate locations: 0
Number of resolved duplicate locations: 0
Number of ignored locations: 0
Importing data for 2020-04-02
Number of processed locations: 2568
Number of duplicate locations: 0
Number of resolved duplicate locations: 0
Number of ignored locations: 1
Importing data for 2020-04-03
Warning: Ambiguous record DailyReport(id=symbol('NO_VALUE'), country_region='US', province_state='Utah', fips='49053', admin2='Washington', last_update=datetime.datetime(2020, 4, 3, 22, 46, 37), confirmed=21, deaths=1, recovered=0, jh_id=84049053): other record has confirmed=2, deaths=0, recovered=0
Number of processed locations: 2622
Number of duplicate locations: 1
Number of resolved duplicate locations: 0
Number of ignored locations: 1
Importing data for 2020-04-04
Warning: Ambiguous record DailyReport(id=symbol('NO_VALUE'), country_region='US', province_state='Utah', fips='49053', admin2='Washington', last_update=datetime.datetime(2020, 4, 4, 23, 34), confirmed=22, deaths=1, recovered=0, jh_id=84049053): other record has confirmed=3, deaths=0, recovered=0
Number of processed locations: 2676
Number of duplicate locations: 1
Number of resolved duplicate locations: 0
Number of ignored locations: 1
Importing data for 2020-04-05
Warning: Ambiguous record DailyReport(id=symbol('NO_VALUE'), country_region='US', province_state='Utah', fips='49053', admin2='Washington', last_update=datetime.datetime(2020, 4, 5, 23, 6, 45), confirmed=22, deaths=1, recovered=0, jh_id=84049053): other record has confirmed=5, deaths=0, recovered=0
Number of processed locations: 2761
Number of duplicate locations: 1
Number of resolved duplicate locations: 0
Number of ignored locations: 1
Importing data for 2020-04-06
Warning: Ambiguous record DailyReport(id=symbol('NO_VALUE'), country_region='US', province_state='Utah', fips='49053', admin2='Washington', last_update=datetime.datetime(2020, 4, 6, 23, 22), confirmed=26, deaths=1, recovered=0, jh_id=84049053): other record has confirmed=5, deaths=0, recovered=0
Number of processed locations: 2806
Number of duplicate locations: 1
Number of resolved duplicate locations: 0
Number of ignored locations: 1
Importing data for 2020-04-07
Number of processed locations: 2856
Number of duplicate locations: 0
Number of resolved duplicate locations: 0
Number of ignored locations: 0
Importing data for 2020-04-08
Number of processed locations: 2882
Number of duplicate locations: 0
Number of resolved duplicate locations: 0
Number of ignored locations: 0
Importing data for 2020-04-09
Number of processed locations: 2910
Number of duplicate locations: 0
Number of resolved duplicate locations: 0
Number of ignored locations: 0
Importing data for 2020-04-10
Number of processed locations: 2940
Number of duplicate locations: 0
Number of resolved duplicate locations: 0
Number of ignored locations: 1
Importing data for 2020-04-11
Number of processed locations: 2964
Number of duplicate locations: 0
Number of resolved duplicate locations: 0
Number of ignored locations: 1
Importing data for 2020-04-12
Number of processed locations: 2987
Number of duplicate locations: 0
Number of resolved duplicate locations: 0
Number of ignored locations: 1
Importing data for 2020-04-13
Number of processed locations: 3001
Number of duplicate locations: 0
Number of resolved duplicate locations: 0
Number of ignored locations: 0
Importing data for 2020-04-14
Number of processed locations: 3013
Number of duplicate locations: 0
Number of resolved duplicate locations: 0
Number of ignored locations: 0
Importing data for 2020-04-15
Number of processed locations: 3026
Number of duplicate locations: 0
Number of resolved duplicate locations: 0
Number of ignored locations: 0
Importing data for 2020-04-16
Number of processed locations: 3041
Number of duplicate locations: 0
Number of resolved duplicate locations: 0
Number of ignored locations: 0
Importing data for 2020-04-17
Number of processed locations: 3045
Number of duplicate locations: 0
Number of resolved duplicate locations: 0
Number of ignored locations: 0
Importing data for 2020-04-18
Unable to fetch report. It may not be available yet.
```

**Comment by MatMoore** [comment]
I'm gonna close this PR now, as I expect the data has changed quite a lot from when this was written. But let me know if you think there's anything useful still to do with this.

**Comment by andreagrandi** [comment]
> I'm gonna close this PR now, as I expect the data has changed quite a lot from when this was written. But let me know if you think there's anything useful still to do with this.

Hey Mat 👋
First of all thank you for your effort, but I also quite "abandoned" the projects months ago for lack of time 😓
I even deactivated the resources used on Heroku (they were going to charge us from Jan 2021) and the domain expired... yesterday!
I'm going to leave the project/code here of course, for anyone else willing to grab it and continue.

**Comment by MatMoore** [comment]
No problem, it was fun to work on 😄

**Pull request closed without merging**
