### PR TITLE
Add /health and /daily-reports endpoints

### PR DESCRIPTION
**Pull request by andreagrandi**
Hi everyone!

This PR adds two simple but working endpoints:
- /v1/health
- /v1/daily-reports

here is an example of the returned data:

Screenshot 2020-03-03 18 12 39

There is a issue: to make it work I had to run `uvicorn covidapi.app:app --reload` from the root of the project **and** copy `covid-reports.db` from `covidapi/` to the root of the project.

If I try to run `uvicorn app:app --reload` from inside `covidapi/` folder, I start getting errors like this:

```
  File "./app.py", line 2, in <module>
    from .api import views
ImportError: attempted relative import with no known parent package
```

We can definitely improve this but I think it's at least "something". What do you think? If you have any suggestions, please let me know!

### CODE REVIEW

**Comment by fundor333** [comment]
The "wrong path of .db" is because the setting is sqlite:///./covid-reports.db and you probably launch import_data from the covidapi and not from the root...

**Comment by fundor333** [comment]
If we use postgresql or other not file db this become a non existing problem

**Comment by andreagrandi** [comment]
> The "wrong path of .db" is because the setting is sqlite:///./covid-reports.db and you probably launch import_data from the covidapi and not from the root...

that's correct. That's why I was trying the opposite which is launching `app.py` from inside the `covidapi` folder.

**Comment by andreagrandi** [comment]
> If we use postgresql or other not file db this become a non existing problem

it should be a matter of changing the connection string, but I'm going to make it easier to do by supporting a default (SQLite) one and reading it from and environment variable.

**Comment by andreagrandi** [comment]
I'm going to merge this later unless there are any other comments in the mean time.

**Comment by MatMoore** [comment]
LGTM. Haven't thought too much yet about what endpoints would be useful but this looks like a reasonable place to start. Should we start writing some tests as well?

It might be worth putting a hard limit on the `limit` parameter because the database could get quite big.

Regarding the relative path issues, I don't have any problem running all the scripts from the project root. Maybe another workaround would be to dynamically construct that URI to be relative to the script instead of the working directory?

**Review by MatMoore — APPROVED** [review]

**Comment by andreagrandi** [comment]
> LGTM. Haven't thought too much yet about what endpoints would be useful but this looks like a reasonable place to start. Should we start writing some tests as well?

Yes, introducing `pytest` is next on my TODO list 👍 

Regarding which endpoints to provide, I've a couple of ideas in mind but I would like to discuss them in a separate issue.

> It might be worth putting a hard limit on the `limit` parameter because the database could get quite big.

limits, possibly invite only access for the beginning (to limit abuse and evaluate how much resources we need) but we need to implement authentication and user management for this (all things that would have been easy peasy with Django Rest Framework, but let's not give up).

> Regarding the relative path issues, I don't have any problem running all the scripts from the project root. Maybe another workaround would be to dynamically construct that URI to be relative to the script instead of the working directory?

yes, it's a possibility, but I consider SQLite as a temporary thing. I'd like to switch to PostgreSQL asap and set the connection string through env variable.

**Pull request merged**
